// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFSCaIvcUeguK5aK1dohaq6OzfpLg3qhQ',
    appId: '1:581433376844:web:5ec7e4a3417a857766b4e9',
    messagingSenderId: '581433376844',
    projectId: 'mobile-verification-3bb83',
    authDomain: 'mobile-verification-3bb83.firebaseapp.com',
    storageBucket: 'mobile-verification-3bb83.appspot.com',
    measurementId: 'G-6GDB3SBSE4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8kgVxSeJ52u6Kr4UVlzBZgeG1z5syegU',
    appId: '1:581433376844:android:677c59a2ce030d4366b4e9',
    messagingSenderId: '581433376844',
    projectId: 'mobile-verification-3bb83',
    storageBucket: 'mobile-verification-3bb83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxd6NQi1hrJZkaQHZ3WcbK16eHHxDkpQM',
    appId: '1:581433376844:ios:a58c43a23db1510e66b4e9',
    messagingSenderId: '581433376844',
    projectId: 'mobile-verification-3bb83',
    storageBucket: 'mobile-verification-3bb83.appspot.com',
    iosBundleId: 'com.example.phoneVerification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxd6NQi1hrJZkaQHZ3WcbK16eHHxDkpQM',
    appId: '1:581433376844:ios:7091f54b6c7d054066b4e9',
    messagingSenderId: '581433376844',
    projectId: 'mobile-verification-3bb83',
    storageBucket: 'mobile-verification-3bb83.appspot.com',
    iosBundleId: 'com.example.phoneVerification.RunnerTests',
  );
}
